---
title: 'Análisis de los determinantes salariales en el mercado moderno: un estudio
  estadístico.'
author: 'Vianney Becerra C.I: 31.375.207 y Santiago lópez López C.I: 30.330.479'
date: "`r Sys.Date()`"
output: pdf_document
toc: true
toc_depth: 2
fontsize: 12pt
number_sections: true
mainfont: "Times new Roman"
indent: true
header-includes:
  header-includes:
   - \usepackage{indentfirst}
   - \setlength{\parindent}{2em}
   - \setlength{\parskip}{1em}
   - \linespread{1.3}
   - \usepackage{fancyhdr}
   - \pagestyle{fancy}
   - \fancyhf{} # Limpia todos los encabezados y pies de página
   - \fancyfoot[R]{\thepage} # Pone el número de página a la derecha (Right)
   - \renewcommand{\headrulewidth}{0pt} # Quita la línea horizontal de arriba
---
\newpage

# Introducción



\newpage

# 1. Planteamiento de la investigación

## 1.1 Planteamiento del Problema

En la última década, el mercado laboral global ha experimentado una transformación sin precedentes. Factores como la digitalización acelerada, la normalización del trabajo remoto y la demanda de habilidades técnicas específicas han redefinido cómo se valoran los puestos de trabajo. Ya no basta con mirar el "título del cargo"; la compensación económica ahora parece estar sujeta a una red compleja de variables interconectadas.

¿Es el tamaño de la empresa un predictor fiable del sueldo? ¿Existe una penalización salarial por elegir la modalidad remota, o es ahora un estándar competitivo? ¿Qué tanto peso real tienen ciertas habilidades (skills) frente a la ubicación geográfica?. A pesar de la abundancia de ofertas de trabajo, existe una falta de claridad sobre cuáles son los verdaderos determinantes del salario en el mercado actual, por lo cual, este estudio busca aclarar esas dudas mediante la estadística descriptiva y el uso de la plataforma GitHub y lenguajes de programación conocidos como R y Python.

# 2. Objetivos

## 2.1 Objetivo General

Analizar el panorama laboral de los sectores tecnológicos emergentes mediante estadística descriptiva para identificar las variables que más impactan en la oferta salarial y la demanda de talento.

## 2.2 Objetivos Específicos

* Determinar el promedio, mediana y desviación estándar de los salarios por industria para identificar cuál es la más rentable.

* Comparar las medias salariales entre puestos remotos y presenciales para verificar si existe una "penalización" o beneficio económico por la modalidad.

* Identificar las ciudades con mayores ofertas de empleo y su nivel de remuneración promedio.

* Clasificar las habilidades más solicitadas en cada sector y su frecuencia de aparición en las vacantes.

* Evaluar si el tamaño de la empresa (Small, Medium, Large) influye significativamente en los rangos salariales ofrecidos.

# 3. Marco de Referencia

## 3.1 Marco Teórico

* **Teoría del Capital Humano:** Teoría del Capital Humano:La Teoría del Capital Humano fué desarrollada en la década de 1960, principalmente por el economista Gary Becker. Propone que el salario está directamente relacionado con la productividad del trabajador, la cual se mide a través de sus habilidades y educación.

* **Teoría de los Salarios Compensatorios:** se refiere a la diferencia salarial que surge para compensar las características no monetarias de los diferentes puestos de trabajo. En esencia, los trabajadores están dispuestos a aceptar salarios más bajos por trabajos que ofrecen atributos más deseables, como un ambiente de trabajo más seguro o horarios más flexibles.

* **Teoría de la segmentación del mercado laboral:** surgió a finales de los años sesenta para explicar fenómenos como las desigualdades salariales, la discriminación y el desempleo. Esta teoría sostiene que el mercado laboral está compuesto por varios segmentos, cada uno con diferentes mecanismos de determinación salarial y barreras a la movilidad entre ellos.

# 4. Marco Metodológico

## 4.1 Enfoque y tipo de investigación

La investigación adopta un **enfoque cuantitativo** de tipo **descriptivo-correlacional**. No sólo busca describir las variables de forma aislada, sino también explorar la existencia y la forma de las relaciones entre ellas, sin llegar a establecer inferencias de causalidad.



